begin;
drop table if exists sg_asistencias cascade;
drop table if exists sg_alumno_curso cascade;
drop table if exists sg_xalumno_curso cascade;
drop table if exists sg_alumnos cascade;
drop table if exists sg_curso_etiqueta cascade;
drop table if exists sg_cursos cascade;
drop table if exists sg_etiquetas cascade;
drop table if exists sg_sesiones cascade;
drop table if exists sg_xcursos cascade;
drop table if exists sg_folios cascade;
commit;